name: "Auto PR: dev to main"

on:
  schedule:
    # At 00:00 on Sunday and Monday
    - cron: '0 0 * * 0,1'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch dev branch
        run: git fetch origin dev:dev

      - name: Check for differences
        id: diffcheck
        run: |
          git diff --quiet main..dev || echo "has_diff=true" >> $GITHUB_OUTPUT

      - name: Switch to dev branch and preserve files
        if: steps.diffcheck.outputs.has_diff == 'true'
        run: |
          echo "Switching to dev branch and preserving files from main..."

          # Switch to dev branch
          git checkout dev

          # Preserve workflow files from main branch
          if git ls-tree -r main --name-only | grep -q "^\.github/workflows/"; then
            echo "GitHub Actions workflows found in main branch"

            # Create .github/workflows directory if it doesn't exist
            mkdir -p .github/workflows/

            # Copy all workflow files from main branch
            git ls-tree -r main --name-only | grep "^\.github/workflows/" | while read file; do
              echo "Preserving workflow file: $file"
              git show main:$file > $file
            done

            echo "GitHub Actions files preserved from main branch"
          else
            echo "No GitHub Actions workflows found in main branch to preserve"
          fi

          # Preserve poem.md from main branch if it exists
          if git show main:poem.md > /dev/null 2>&1; then
            echo "Preserving poem.md from main branch"
            git show main:poem.md > poem.md
          else
            echo "No poem.md found in main branch to preserve"
          fi

      - name: Create Pull Request
        if: steps.diffcheck.outputs.has_diff == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Preserve GitHub Actions workflows and poem.md from main branch"
          title: "Automated PR: Merge dev into main (with preserved workflows)"
          body: |
            This pull request was automatically created by a scheduled workflow.
            It merges changes from `dev` into `main` while preserving GitHub Actions workflows.

            **Preserved files:**
            - All `.github/workflows/` files from main branch
            - poem.md from main branch

            **Changes included:**
            - All updates from dev branch
          base: main
          reviewers: krugou
          draft: false
