name: "Auto PR: dev to main"

on:
  schedule:
    # At 00:00 on Sunday and Monday
    - cron: '0 0 * * 0,1'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch dev branch
        run: git fetch origin dev:dev

      - name: Check for differences
        id: diffcheck
        run: |
          git diff --quiet main..dev || echo "has_diff=true" >> $GITHUB_OUTPUT

      - name: Preserve GitHub Actions files
        if: steps.diffcheck.outputs.has_diff == 'true'
        run: |
          echo "Preserving GitHub Actions files from main branch..."

          # Set up Git identity for commits
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create temporary branch from dev
          git checkout -b temp-merge-branch dev

          # Preserve workflow files from main branch
          if git ls-tree -r main --name-only | grep -q "^\.github/workflows/"; then
            echo "GitHub Actions workflows found in main branch"

            # Create .github/workflows directory if it doesn't exist
            mkdir -p .github/workflows/

            # Copy all workflow files from main branch
            git ls-tree -r main --name-only | grep "^\.github/workflows/" | while read file; do
              echo "Preserving workflow file: $file"
              git show main:$file > $file
            done

            echo "GitHub Actions files preserved from main branch"

            # Commit preserved files if any changes
            git add .github/workflows/
            if ! git diff --cached --quiet; then
              git commit -m "Preserve GitHub Actions workflows from main branch"
              echo "Committed preserved workflow files"
            fi
          else
            echo "No GitHub Actions workflows found in main branch to preserve"
          fi

      - name: Create Pull Request from dev to main
        if: steps.diffcheck.outputs.has_diff == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: temp-merge-branch
          base: main
          title: "Automated PR: Merge dev into main (with preserved workflows)"
          body: |
            This pull request was automatically created by a scheduled workflow.
            It merges changes from `dev` into `main` while preserving GitHub Actions workflows.

            **Preserved files:**
            - All `.github/workflows/` files from main branch

            **Changes included:**
            - All updates from dev branch
          reviewers: |
            GitHub Copilot
          draft: false
