name: Mirror GitLab main Branch to dev Branch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write
jobs:
  mirror-gitlab-main-to-dev:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove all files except .git
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Clone GitLab main branch
        run: |
          git clone --single-branch --branch devmain --depth 1 "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}" gitlab-src
        continue-on-error: false

      - name: Show latest commit from GitLab
        run: |
          cd gitlab-src
          echo "Latest commit in GitLab on branch:"
          git rev-parse --abbrev-ref HEAD
          git log -1 --oneline || echo "No commits found"
          cd ..

      - name: Copy files from GitLab repo
        run: |
          shopt -s dotglob
          cp -r gitlab-src/* .
          rm -rf gitlab-src

      - name: Set GitHub remote
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Show repository info
        run: |
          echo "Repository name from environment: $GITHUB_REPOSITORY"
          git remote -v
          git branch -a
          git status
          git config --get remote.origin.url

      - name: Commit and push changes to dev branch
        run: |
          git add .
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Mirror from GitLab main: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git push origin dev
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Log success
        run: echo "Mirror from GitLab main branch completed successfully."

    # Error handling is provided by 'continue-on-error: false' and workflow logs.
