name: Mirror GitLab main Branch to dev Branch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write
jobs:
  mirror-gitlab-main-to-dev:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create date-based branch name
        run: |
          BRANCH_DATE=$(date -u +"%d%m%H%M")
          MIRROR_BRANCH="mirror-$BRANCH_DATE"
          echo "MIRROR_BRANCH=$MIRROR_BRANCH" >> $GITHUB_ENV
          echo "Creating mirror branch: $MIRROR_BRANCH"

      - name: Create and checkout new mirror branch
        run: |
          git checkout -b $MIRROR_BRANCH
          echo "Created and switched to branch: $MIRROR_BRANCH"

      - name: Remove all files except .git
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Clone GitLab main branch
        run: |
          git clone --single-branch --branch devmain --depth 1 "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}" gitlab-src
        continue-on-error: false

      - name: Show latest commit from GitLab
        run: |
          cd gitlab-src
          echo "Latest commit in GitLab on branch:"
          git rev-parse --abbrev-ref HEAD
          git log -1 --oneline || echo "No commits found"
          echo "GitLab commit hash:"
          git rev-parse HEAD
          echo "GitLab commit date:"
          git log -1 --format="%cd" --date=iso
          cd ..

      - name: Copy files from GitLab repo into gitlab-copy directory
        run: |
          echo "Copying files from GitLab repository..."

          # Check if gitlab-src directory exists and has content
          if [ -d "gitlab-src" ]; then
            echo "GitLab source directory found"
            echo "GitLab source contents:"
            ls -la gitlab-src/

            echo "Current GitHub repo contents before copy:"
            ls -la

            # Create gitlab-copy directory for clearer organization
            mkdir -p gitlab-copy

            # Use rsync for reliable copying, excluding .git directory
            # This preserves file permissions and handles all file types properly
            rsync -av --progress --exclude='.git' gitlab-src/ gitlab-copy/

            echo "Files copied successfully using rsync to gitlab-copy directory"
            echo "GitLab copy directory contents:"
            ls -la gitlab-copy/

            # Show file count comparison
            echo "File count in GitLab source: $(find gitlab-src -type f | wc -l)"
            echo "File count in gitlab-copy: $(find gitlab-copy -type f | wc -l)"

            # Now move files from gitlab-copy to current directory
            echo "Moving files from gitlab-copy to current directory..."
            rsync -av gitlab-copy/ ./

            echo "Current directory contents after moving files:"
            ls -la

            # Clean up temporary directories
            rm -rf gitlab-src gitlab-copy
          else
            echo "ERROR: gitlab-src directory not found!"
            exit 1
          fi

      - name: Set GitHub remote
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Debug current state
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Files in current directory:"
          ls -la
          echo "Git status:"
          git status

      - name: Commit all changes to mirror branch
        run: |
          echo "Preparing to commit changes..."
          echo "Current branch: $(git branch --show-current)"

          # Add all changes
          git add -A

          echo "Git status after adding files:"
          git status

          echo "Files to be committed (detailed):"
          git status --porcelain

          echo "Checking if there are any changes to commit:"
          if git diff --cached --quiet; then
            echo "No changes detected to commit"
            echo "This might mean:"
            echo "1. Files are identical between GitLab and GitHub"
            echo "2. Files weren't copied properly"
            echo "3. All changes were already committed"

            echo "Checking for untracked files:"
            git ls-files --others --exclude-standard

            # Force commit anyway to update timestamp
            git commit -m "Mirror from GitLab devmain: $(date -u +"%Y-%m-%d %H:%M:%S UTC") - Branch: $MIRROR_BRANCH (no changes detected)" --allow-empty
          else
            echo "Changes detected, committing..."
            echo "Changed files:"
            git diff --cached --name-only
            git commit -m "Mirror from GitLab devmain: $(date -u +"%Y-%m-%d %H:%M:%S UTC") - Branch: $MIRROR_BRANCH"
          fi

          echo "Commit created successfully"
          echo "Latest commit info:"
          git log -1 --oneline

          echo "Pushing mirror branch to GitHub..."
          git push origin $MIRROR_BRANCH --force

          echo "Push completed. Branch $MIRROR_BRANCH should now be visible on GitHub."
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      # - name: Switch to dev and merge
      #   run: |
      #     git checkout dev
      #     echo "Merging $MIRROR_BRANCH into dev..."
      #     git merge $MIRROR_BRANCH --no-ff -m "Merge mirror branch $MIRROR_BRANCH into dev - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
      #     echo "Pushing dev branch..."
      #     git push origin dev

      # - name: Clean up mirror branch
      #   run: |
      #     git push origin --delete $MIRROR_BRANCH || echo "Failed to delete remote branch, continuing..."

      - name: Log success
        run: echo "Mirror from GitLab devmain branch to dev completed successfully via branch $MIRROR_BRANCH."


