name: Mirror GitLab main Branch to dev Branch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write
jobs:
  mirror-gitlab-main-to-dev:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove all files except .git
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Clone GitLab main branch
        run: |
          git clone --single-branch --branch devmain --depth 1 "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}" gitlab-src
        continue-on-error: false

      - name: Copy files from GitLab repo
        run: |
          if [ -d "gitlab-src" ]; then
            mkdir -p gitlab-copy
            rsync -av --exclude='.git' gitlab-src/ gitlab-copy/
            rsync -av gitlab-copy/ ./
            rm -rf gitlab-src gitlab-copy
          else
            echo "ERROR: gitlab-src directory not found!"
            exit 1
          fi

      - name: Set GitHub remote
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Commit and push changes to dev branch
        run: |
          git add -A
          if git diff --cached --quiet; then
            git commit -m "Mirror from GitLab devmain: $(date -u +"%Y-%m-%d %H:%M:%S UTC") (no changes detected)" --allow-empty
          else
            git commit -m "Mirror from GitLab devmain: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          fi
          git push origin dev
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Log success
        run: echo "Mirror from GitLab devmain branch to dev completed successfully."


