name: Mirror GitLab main Branch to dev Branch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write
jobs:
  mirror-gitlab-main-to-dev:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create date-based branch name
        run: |
          BRANCH_DATE=$(date -u +"%d%m")
          MIRROR_BRANCH="mirror-$BRANCH_DATE"
          echo "MIRROR_BRANCH=$MIRROR_BRANCH" >> $GITHUB_ENV
          echo "Creating mirror branch: $MIRROR_BRANCH"

      - name: Create and checkout new mirror branch
        run: |
          git checkout -b $MIRROR_BRANCH
          echo "Created and switched to branch: $MIRROR_BRANCH"

      - name: Remove all files except .git
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      - name: Clone GitLab main branch
        run: |
          git clone --single-branch --branch devmain --depth 1 "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}" gitlab-src
        continue-on-error: false

      - name: Show latest commit from GitLab
        run: |
          cd gitlab-src
          echo "Latest commit in GitLab on branch:"
          git rev-parse --abbrev-ref HEAD
          git log -1 --oneline || echo "No commits found"
          echo "GitLab commit hash:"
          git rev-parse HEAD
          echo "GitLab commit date:"
          git log -1 --format="%cd" --date=iso
          GITLAB_DATE=$(git log -1 --format="%ct")
          echo "GITLAB_TIMESTAMP=$GITLAB_DATE" >> $GITHUB_ENV
          cd ..

      - name: Copy files from GitLab repo
        run: |
          shopt -s dotglob
          cp -r gitlab-src/* .
          rm -rf gitlab-src

      - name: Set GitHub remote
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Commit all changes to mirror branch
        run: |
          git add .
          echo "Files to be committed:"
          git status --porcelain
          git commit -m "Mirror from GitLab devmain: $(date -u +"%Y-%m-%d %H:%M:%S UTC") - Branch: $MIRROR_BRANCH" --allow-empty
          echo "Pushing mirror branch to GitHub..."
          git push origin $MIRROR_BRANCH
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Merge mirror branch to dev
        run: |
          git checkout dev
          git merge $MIRROR_BRANCH --no-ff -m "Merge mirror branch $MIRROR_BRANCH into dev"
          git push origin dev

      - name: Clean up mirror branch
        run: |
          git branch -d $MIRROR_BRANCH
          git push origin --delete $MIRROR_BRANCH

      - name: Log success
        run: echo "Mirror from GitLab devmain branch to dev completed successfully via branch $MIRROR_BRANCH."

    # Error handling is provided by 'continue-on-error: false' and workflow logs.
        git config --get remote.origin.url

      - name: Commit and push changes to dev branch
        run: |
          git add .
          echo "Changes to be committed:"
          git diff --cached --name-only || echo "No staged changes"
          echo "Force update flag: $FORCE_UPDATE"

          if [ "$FORCE_UPDATE" = "true" ] || ! git diff --cached --quiet; then
            if [ "$FORCE_UPDATE" = "true" ]; then
              echo "Force updating due to newer GitLab changes"
              git commit -m "Force mirror from GitLab devmain: $(date -u +"%Y-%m-%d %H:%M:%S UTC") - GitLab has newer changes" --allow-empty
            else
              git commit -m "Mirror from GitLab devmain: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            fi
            echo "Pushing to GitHub dev branch..."
            git push origin dev --force
          else
            echo "No changes to commit and no force update needed"
          fi
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Log success
        run: echo "Mirror from GitLab main branch completed successfully."

    # Error handling is provided by 'continue-on-error: false' and workflow logs.
